# ------------------------------------------------------------------------
# PRIMARY BUTTON (call to action)
# -------------------------------------------------------------------------
# name - internal label (string)
# priority - position in group (number)
# url - link (string)
# tab - open in new tab (boolean; default: false)
# text - button text (string)
# icon - file name (string; optional; located in "/static/icons" folder)
# disabled - disable link (boolean; default: false)
# visible - show on index page (boolean)
# ------------------------------------------------------------------------

- button:
  name: "launcher"
  priority: 1
  url: "link-to-launcher"
  tab: true
  text: "Coming soon"
  icon: ""
  disabled: true
  visible: true
- button:
  name: "patreon"
  priority: 2
  url: "https://www.patreon.com/purpleworld"
  tab: true
  text: "Patreon"
  icon: ""
  disabled: false
  visible: true
