# ------------------------------------------------------------------------
# PRIMARY BUTTONS
# -------------------------------------------------------------------------
# name - internal label (string)
# priority - position in group (number)
# url - link (string)
# tab - open in new tab (boolean; default: false)
# text - button text (string)
# icon - file name (string; optional; located in "/static/icons" folder)
# disabled - disable link (boolean; default: false)
# visible - show on index page (boolean)
# ------------------------------------------------------------------------

- button:
  name: "launcher"
  priority: 1
  url: "launcher"
  tab: false
  text: "Download launcher"
  icon: ""
  disabled: false
  visible: true
- button:
  name: "patreon"
  priority: 2
  url: "https://purpleworld.net"
  tab: true
  text: "Forums"
  icon: ""
  disabled: false
  visible: true
