# ------------------------------------------------------------------------
# SECONDARY BUTTONS
# ------------------------------------------------------------------------
# name - internal label (string)
# priority - position in group (number)
# url - link (string)
# tab - open in new tab (boolean; default: false)
# icon - file name (string; located in "/static/icons" folder)
# disabled - disable link (boolean; default: false)
# visible - show on index page (boolean; default: false)
# ------------------------------------------------------------------------

- button:
  name: "fivem"
  priority: 1
  url: "link-to-fivem"
  tab: true
  icon: "fivem.svg"
  disabled: false
  visible: false 
- button:
  name: "discord"
  priority: 2
  url: "link-to-discord"
  tab: true
  icon: "discord.svg"
  disabled: false
  visible: false 
- button:
  name: "teamspeak"
  priority: 3
  url: "link-to-teamspeak"
  tab: true
  icon: "teamspeak.svg"
  disabled: false
  visible: false 
  