# ------------------------------------------------------------------------
# INDEX PAGE
# ------------------------------------------------------------------------
# title - main text (long text)
# desc - description text (long text)
# ------------------------------------------------------------------------

title: |
  Lorem ipsum dolor sit amet
  consectetuer adipiscing elita
desc: | 
  Nulla quis diam. Etiam bibendum elit eget erat. In dapibus augue non sapien. Etiam posuere lacus quis dolor.
