# ------------------------------------------------------------------------
# INDEX PAGE
# ------------------------------------------------------------------------
# title - main text (long text)
# desc - description text (long text)
# ------------------------------------------------------------------------

title: |
  Your favorite purple
  FiveM roleplay community
desc: | 
  Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
